### ISSUE TITLE
getAsset not exported?

### ISSUE THREAD

**Issue by ByronBecker** [junobuild/juno-js#171]
When trying to use the `getAsset` API I receive this error:

```
import {listAssets, getAsset, uploadBlob} from "@junobuild/core";
                    ^^^^^^^^
SyntaxError: The requested module '@junobuild/core' does not provide an export named 'getAsset'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12
```

However, the `get_asset` canister endpoint exists on my satellite (via the Candid UI).

**Comment by peterpeterparker** [comment]
I just updated the NodeJS [basic](https://github.com/junobuild/examples/tree/main/node/basic) example and added an [assets](https://github.com/junobuild/examples/blob/main/node/basic/assets.mjs) sample containing a `getAsset`. 

What version of the library are you using?

You can also try to use `@junobuild/core-peer` instead of `@junobuild/core` maybe?

The 'core' package includes agent-js within the library, whereas 'core-peer' relies on agent-js as peer dependencies. Depending on the environment, one may work better than the other. The ultimate goal is to use 'core' universally, but bundling agent-js is currently challenging unfortunately.
